name: Puppet Google Chrome CI

on:
  push:
    paths-ignore:
      - '**.md'
      - 'LICENSE'
  pull_request:
    paths-ignore:
      - '**.md'
      - 'LICENSE'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7'
      - name: Checkout
        uses: actions/checkout@v2
      - name: Restore Cache
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Bundle Install
        run: |
          bundle install --path vendor/bundle
      - name: Rake Test
        run: |
          bundle exec rake spec

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7'
      - name: Checkout
        uses: actions/checkout@v2
      - name: Restore Cache
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Bundle Install
        run: |
          bundle install --path vendor/bundle
      - name: Puppet Lint
        run: |
          bundle exec puppet-lint manifests --fail-on-warnings --no-documentation-check --no-autoloader_layout-check --no-class_inherits_from_params_class-check

  integration-test:
    runs-on: ubuntu-latest
    needs: 
      - test
      - lint
    strategy:
      fail-fast: false
      matrix:
        os: [ 'centos' , 'debian', 'fedora', 'suse', 'ubuntu' ]      
    steps:
      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7'
      - name: Checkout
        uses: actions/checkout@v2
      - name: Restore Cache
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Bundle Install
        run: |
          bundle install --path vendor/bundle
      - name: Integration Test - ${{ matrix.os }}
        run: |
          docker build -f dockerfiles/${{ matrix.os }} -t jamesnetherton/google-chrome-${{ matrix.os }} .
          docker run --rm jamesnetherton/google-chrome-${{ matrix.os }}

  module-build:
    if: contains(github.ref, 'refs/tags')
    runs-on: ubuntu-latest
    needs: integration-test
    steps:
      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7'
      - name: Checkout
        uses: actions/checkout@v2
      - name: Restore Cache
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Bundle Install
        run: |
          bundle install --path vendor/bundle
      - name: Puppet Module Build
        run: |
          bundle exec puppet module build
      - name: Upload Module
        uses: actions/upload-artifact@v2
        with:
          name: puppet-google-chrome
          path: ./pkg/*.tar.gz
